import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import {Footer, Navbar} from "@/app/components";
import Providers from "@/app/providers";


const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


    return (
    <html lang="en">
    <Providers>
      <body
          className={montserrat.className}>
          <Navbar />
        {children}
      <Footer />
      </body>
    </Providers>
    </html>
  );
}

